### ISSUE TITLE
CocoaPods update

### ISSUE THREAD

**Issue by gvieira** [lakesoft/LKBadgeView#3]
Hey there,

Thanks for the great badge. Save me lot of time!

Anyway, you've recently merged a nice pull request and it would be great to have it on CocoaPods. I know we already have version 1.0.0 there, but what about releasing a 1.1.0?

Don't know if it is you who update CocoaPods repo, but I think (not so sure) you need to create a new tag. Am I right?

Thanks in advance!
Vieira

**Comment by xcatsan** [comment]
Hi,

I create a new tag '1.1.0'.
But I do not know how to update CocoaPods repos..

Thank you a lot !
Hiroshi

**Comment by ened** [comment]
@xcatsan check this document for instructions: http://docs.cocoapods.org/guides/creating_and_maintaining_a_pod.html

**Comment by karlbecker** [comment]
Nice library! Going to try it out with iOS 7 shortly, hope it works fine.

Just wanted to note that this Issue could be closed!
