### ISSUE TITLE
it's not a circle when text is "1"

### ISSUE THREAD

**Issue by wuyongrui** [lakesoft/LKBadgeView#9]
![image](https://cloud.githubusercontent.com/assets/15663448/13344249/587cae42-dc8f-11e5-86df-51d49238e118.png)

```
    LKBadgeView *view = [[LKBadgeView alloc] initWithFrame:CGRectMake(50, 50, 50, 30)];
    [view setText:@"1"];
    [self.view addSubview:view];

    LKBadgeView *view2 = [[LKBadgeView alloc] initWithFrame:CGRectMake(80, 50, 50, 30)];
    [view2 setText:@"2"];
    [self.view addSubview:view2];
```

**Comment by RiceLinTW** [comment]
I got the same problem and just fixed it by not setting the text font.
Hope this could help you.

**Comment by wuyongrui** [comment]
it weird it normal today (not setting the font), thanks anyway @RiceLinTW .
